apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-fabric
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx-gateway-fabric
    repoURL: ghcr.io/nginx/charts
    targetRevision: 2.3.0 # Match the current version
    helm:
      parameters:
        - name: nginx.service.type
          value: LoadBalancer # Change to NodePort if on a local cluster
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true