apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: retail-app-gateway
  namespace: subbu-1-ns
spec:
  gatewayClassName: nginx 
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same